# Development image
FROM debian:buster-slim
SHELL ["/bin/bash", "-c"]
RUN apt update &&\
    apt install -y curl make unzip zip &&\
    apt clean &&\
    curl -s "https://get.sdkman.io" | bash  && source "/root/.sdkman/bin/sdkman-init.sh" &&\
    sdk install java 21.0.4-tem &&\
    sdk install scala 3.4.1
