Link resources to test execution directory, TESTDIR is provided by cram and points to the directory containing the run.t file
  $ ln -s ${TESTDIR}/../ydoc.jar ydoc.jar

Yadladoc can be run in two modes 'check' and 'run'
  $ java -jar ydoc.jar --help
  Usage: yadladoc {run|check} <markdown_file>
      run  : generate documentation code from snippets in <markdown_file>
      check: validate that the currrent documentation code is identical to what would be generated by 'run'
