
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        apps: cs scala3 scalafmt
        jvm: adoptium:1.21.0.3

    - name: Enforce formatting
      run: make fmt-check

    - name: Test
      run: make test

    - name: Enforce documentation validity
      run: make doc-check
