
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name'     
        required: true
        default: 'snapshot'
      text:
        description: 'Release description'
        required: true
        default: 'Snapshot build of the main branch'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        apps: cs scala3 scalafmt
        jvm: graalvm-java21:21.0.2

    - name: Enforce formatting
      run: make fmt-check

    - name: Test
      run: make test

  doc-check:
    # doc-check tasks on linux github runners encountered the following error with JShell:
    # "java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Scope$StarImportScope.isFilled()" because "tree.starImportScope" is null"
    # therefore, we use a windows runner for this specific task
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        apps: cs scala3 scalafmt
        jvm: graalvm-java21:21.0.2

    - name: Enforce documentation validity
      run: make doc-check
  
  release:
    runs-on: ubuntu-latest
    needs: [test, doc-check]
    if: github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        apps: cs scala3 scalafmt
        jvm: graalvm-java21:21.0.2

    - name: Package
      # TODO could be retrieved from and earlier job
      run: make usage/ydoc.jar

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.event.inputs.name }}
        tag_name: ${{ github.event.inputs.name }}
        target_commitish: main
        body: ${{ github.event.inputs.text }}
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          usage/ydoc.jar